# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'rgl/windows-server-2012-r2-standard-amd64'
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 8192
    vb.cpus = 4
  end

  config.vm.network 'forwarded_port', guest: 3389, host: 3389
  config.vm.provision 'shell', path: '../scripts/bootstrap.ps1', env: { 'RUBY_VERSION' => '2.5.8' }
  profile_destination = 'C:\Users\vagrant\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'
  config.vm.provision 'file', source: '../scripts/profile.ps1', destination: profile_destination
end
