# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'gusztavvargadr/windows-server-2019-standard'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 8192
    vb.cpus = 4
  end

  config.vm.provision 'shell', path: '../scripts/bootstrap.ps1'
  profile_destination = 'C:\Users\vagrant\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'
  config.vm.provision 'file', source: '../scripts/profile.ps1', destination: profile_destination
end
