# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'rgl/windows-server-2016-standard-amd64'
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 8192
    vb.cpus = 4
  end

  config.vm.define 'server' do |node|
    config.bolt.verbose = true
    node.bolt.port = 55_985
    node.vm.provision :bolt do |bolt|
      bolt.project = '../bootstrap'
      bolt.command = :plan
      bolt.name = 'bootstrap'
    end
  end


  config.vm.network 'forwarded_port', guest: 3389, host: 3389
  profile_destination = 'C:\Users\vagrant\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'
  config.vm.provision 'file', source: '../scripts/profile.ps1', destination: profile_destination
end
